### PR TITLE
Support customizing terminal in macos

### PR DESCRIPTION
**Pull request by adispring**

### CODE REVIEW

**Comment by davidshepherd7** [comment]
Hi, thanks for the pr!

What's the advantage of doing this vs customising `terminal-here-terminal-command` (which is the usual way of running a terminal other than the default)?

**Comment by adispring** [comment]
This may let newbies like me (who have no or little knowledge about elisp) easier to switch to different terminal.

Just switch between `iTerm.app` and `Terminal.app` is enough, no need to learn elisp syntax such as `list`, `function` etc. 

And these two terminals are most frequently used terminal in macos.

**Comment by Kazark** [comment]
I would make use of this for sure.

**Comment by Kazark** [comment]
In the meantime, this is at least good documentation to me for how to do it.

**Comment by davidshepherd7** [comment]
Yeah I think I want to use something like this to make configuring other terminals easier. I haven't merged this yet because I want to think it through from scratch to make sure it handles everything consistently (e.g. all OSes, tramp files) without having to make a breaking change.

**Comment by davidshepherd7** [comment]
Hi @adispring! In issue #25 you asked about using iTerm2, but here you seem to have used iTerm. Is there a difference? 

Wikipedia seems to imply that iTerm is dead and everyone uses iTerm2 instead. Is that right?

**Comment by adispring** [comment]
After installing iTerm2 into MacOS, its name in Application Folder is `iTerm.app`, instead of `iTerm2.app`.

**Comment by davidshepherd7** [comment]
> After installing iTerm2 into MacOS, its name in Application Folder is `iTerm.app`, instead of `iTerm2.app`.

Oh, that's really weird. Their Makefile [seems to build it as `iTerm2.app`](https://github.com/gnachman/iTerm2/blob/master/Makefile#L23). Does `iTerm2.app` work as well?

**Comment by davidshepherd7** [comment]
@adispring @Kazark If you get a chance could you try out the V2 branch and let me know what you think please? It has a completely redone way of customising things based on the idea of this PR.

I haven't updated the readme yet, but the docs in the the custom variables should be good enough.

**Comment by adispring** [comment]
> > After installing iTerm2 into MacOS, its name in Application Folder is `iTerm.app`, instead of `iTerm2.app`.
> 
> Oh, that's really weird. Their Makefile [seems to build it as `iTerm2.app`](https://github.com/gnachman/iTerm2/blob/master/Makefile#L23). Does `iTerm2.app` work as well?

No, `iTerm2.app` does not work in MacOS.

Maybe here is the reason that explains why its Application Name is `iTerm.app` instead of `iTerm2.app`: https://gitlab.com/gnachman/iterm2/-/blob/master/tools/release_stable.sh#L64

**Comment by Kazark** [comment]
Wow, so first of all, looking over this code, it's a magnificent sight. I love the overall drift here, and am amazed by the thoroughness.

Here's what I did to try it. Without any reading of documentation, I blindly forged ahead. I overwrote my `terminal-here.el` with the new version, and `eval`'d the buffer without restarting Emacs. Then I `(setq terminal-here-mac-terminal-command 'iterm2)` and tried launching a terminal. I got:

> Error: in terminal here, command ‘open -a open . --args -a iTerm.app .‘ exited with error code 1

so I thought, "Well, duh, I should unset `terminal-here-terminal-command`", so I did `(setq terminal-here-terminal-command nil)` and tried again. Then I got:

> Error: in terminal here, command ‘open -a iTerm2.app . --args‘ exited with error code 1

The problem here seems to be the presence of `--args`, as the command the gets it working for me when I revert to the old version is `(setq terminal-here-terminal-command '("open" "-a" "iTerm.app" "."))`.

Overall, I looks like you're really close, and this will be yet another amazing DWIM experience that is part of what makes Emacs so great.

**Comment by davidshepherd7** [comment]
@adispring Thanks for figuring that out, I've fixed it to use the right name now.

@Kazark Thanks for testing! Can you try it again now please?

I've changed it so that we won't add "open -a" etc to a command that already has it (so your old command should work on upgrade) and to use `iTerm.app` as the binary name instead of `iTerm2.app` (I think that was the issue, not the `--args` flag, or at least I hope so)

**Comment by adispring** [comment]
I have just tested the newest V2 code, it works in MacOS.

**Comment by Kazark** [comment]
Works for me on Mac as well. :100: 

However on Manjaro with KDE, doesn't work as I would expect. I do not have any `terminal-here-terminal-command` set, but it complains and asks me to set one---whereas based on the code I expected it to just select `konsole`. Turns out that by default, `terminal-here-terminal-command` is set to `terminal-here-default-terminal-command`, which means that this `or`:

```emacs-lisp
(defun terminal-here--os-terminal-command ()
  (or
   terminal-here-terminal-command
   (when (equal system-type 'gnu/linux) terminal-here-linux-terminal-command)
   (when (equal system-type 'darwin) terminal-here-mac-terminal-command)
   (when (or (equal system-type 'ms-dos)
             (equal system-type 'windows-nt)
             (equal system-type 'cygwin))
     terminal-here-windows-terminal-command)
   (user-error "No terminal configuration found for OS %s" system-type)))
```
will always return `terminal-here-terminal-command` until I explicitly `setq` it to `nil`. At that point, it opens Konsole. This behavior is unexpected, since it doesn't seem to fit with the automagical idea of this new branch; nor is it intuitive that to set `terminal-here-terminal-command` to `nil` will actually lead to nicer behavior.

Should `terminal-here-terminal-command` be set to `nil` by default rather than `terminal-here-default-terminal-command`?

**Comment by adispring** [comment]
@Kazark 
I search through the `terminal-here.el` file, not find `terminal-here-default-terminal-command`. And `terminal-here-terminal-command` is set to `nil`, no other customize.

Do you restart Emacs after copied V2 code?

**Comment by Kazark** [comment]
@adispring ah, I wonder if it is a Spacemacs thing. Let me look into it a little deeper.

**Comment by Kazark** [comment]
@adispring oh, oh, I see, this is a relic of the defaults of v1, thus your comment about restarting Emacs. No, I didn't restart Emacs---but I see that if I had, this would have resolved itself. 👍

**Comment by davidshepherd7** [comment]
Great, thanks for the help and ideas!. I've merged the v2 changes to master now so there should be a melpa release up in a few hours.

**Pull request closed without merging**
